name: Gerar infor Chart

on:
  schedule:
    - cron: '0 6 * * *' # Executa todos os dias às 6:00 da manha
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Atualizado para v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python gerar_infor.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git pull origin main  # Adicione esta linha para fazer pull das mudanças
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m 'Update infor chart'
          git push origin main
        else
          echo "No changes to commit"
        fi
